name: Deploy SvelteKit

on:
  push:
    branches: [ "main" ]

permissions:
  contents: 'read'
  id-token: 'write'

env:
  PROJECT_ID: 'a-story-to-write'
  PROJECT_NUMBER: ${{ secrets.PROJECT_NUMBER }}
  REGION: 'europe-west9'
  SA_EMAIL: 'github-actions-sa@a-story-to-write.iam.gserviceaccount.com'
  POOL: 'github-pool'
  PROVIDER: 'github-provider'
  REPOSITORY: 'sveltekit-repo'
  SERVICE_NAME: 'cloud-run-sveltekit'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/${{ env.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ env.POOL }}/providers/${{ env.PROVIDER }}'
          service_account: ${{ env.SA_EMAIL }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Authorize Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          IMAGE_URI="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE_NAME }}:${{ github.sha }}"
          docker build -t "$IMAGE_URI" .
          docker push "$IMAGE_URI"

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
          secrets: |
            HF_TOKEN=hf-secret:latest
          flags: '--allow-unauthenticated'